Added schema updated and relevant test case for client with default_organization
auth0/terraform-provider-auth0 pull request #1009
Opened 2024-08-26 05:52 UTC by duedares-rvj

…organization

### 🔧 Changes

### 📚 References

### 🔬 Testing

### 📝 Checklist

- [ ] All new/changed/fixed functionality is covered by tests (or N/A)
- [ ] I have added documentation for all new/changed functionality (or N/A)

2024-08-26 14:43 UTC, acwest requested changes

2024-08-26 14:43 UTC, acwest commented on internal/auth0/client/resource_test.go
We should add a test for adding and removing the `default_organization`

2024-08-28 09:48 UTC, duedares-rvj commented on internal/auth0/client/resource_test.go
Ack!
Update the test case to include a delete flow.

2024-08-28 09:49 UTC, duedares-rvj commented on internal/auth0/client/resource_test.go
> +			//{
@acwest For some reason, I'm not able to test this case. Let's have a quick word when you get a chance.

2024-08-30 20:49 UTC, acwest commented
You have a couple of linting issues and test failures yet

2024-08-30 20:49 UTC, acwest commented
Looks pretty good otherwise

2024-09-05 09:28 UTC, developerkunal requested changes

2024-09-05 09:28 UTC, developerkunal commented on test/data/recordings/TestAccTemp.yaml
@duedares-rvj can we remove this recording?

2024-09-05 09:32 UTC, duedares-rvj commented on test/data/recordings/TestAccTemp.yaml
Removed.

2024-09-05 14:19 UTC, developerkunal approved these changes
LGTM

2024-09-05 14:23 UTC, acwest commented on internal/auth0/client/resource_test.go
that was more complicated than expected...

2024-09-05 19:57 UTC, acwest approved these changes

2024-09-06 05:40 UTC, merged