Description of connection level parameter
auth0/terraform-provider-auth0 pull request #653
Opened 2023-06-22 12:42 UTC by kopernic-pl

Description added per what's in Auth0 frontend next to this parameter.

### 🔧 Changes

Description of parameter added.

### 📚 References

<img width="657" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/3717613/47d9baa7-b3e8-49ca-be58-3e097bb8e5d1">
As on attached image.

### 🔬 Testing

build run locally, passing

### 📝 Checklist

- [ N/A] All new/changed/fixed functionality is covered by tests (or N/A)
- [ N/A] I have added documentation for all new/changed functionality (or N/A)

2023-07-03 14:25 UTC, sergiught requested changes
Hey @kopernic-pl 👋🏻 thanks for the contribution! Would you mind running a quick made docs and commit any changed files as well? 🙏🏻

2023-07-03 14:25 UTC, sergiught commented on internal/auth0/connection/schema.go
> +						"Front Channel will use OIDC protocol with response_mode=form_post and response_type=id_token. " +
```suggestion
						"Front Channel will use OIDC protocol with `response_mode=form_post` and `response_type=id_token`. " +
```

2023-07-03 14:26 UTC, sergiught commented on internal/auth0/connection/schema.go
> + 						"Back Channel will use response_type=code.",
```suggestion
 						"Back Channel will use `response_type=code`.",
```

2023-07-04 05:07 UTC, kopernic-pl commented
`make docs` change committed. Re-review requested.

2023-07-05 13:40 UTC, sergiught approved these changes
Thanks a lot for the contribution @kopernic-pl 💯

2023-07-05 13:40 UTC, merged